// Generated by https://quicktype.io

export interface Cliente {
  id:        number;
  names:     string;
  surnames:  string;
  email:     string;
  phone:     string;
  address:   string;
  status:    boolean;
  planId:    number;
  trainerId: number;
}
